# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCuqRYbJAGhEq-F3e3lRy_mV-0xoTcCz
"""

import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread('sample1.jpg')

# Check if image was loaded successfully
if img is None:
    print("Error: Could not read the image. Please ensure 'sample1.jpg' exists and is accessible.")
else:
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    cv2_imshow(gray_img) # Corrected typo: gray_image to gray_img
    cv2.imwrite('gray_image.jpg', gray_img)

# cv2.waitKey(0) and cv2.destroyAllWindows() are generally not needed in Colab notebooks with cv2_imshow