# -*- coding: utf-8 -*-
"""CO2AT2Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1KfJGT9zs4GcWNxkgHEq8yoiO9HLoim
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read grayscale image
image = cv2.imread("sample.jpg", cv2.IMREAD_GRAYSCALE)

# Convert image to float
image_float = image.astype(np.float32)

# Apply logarithm
log_image = np.log1p(image_float)

# Apply Gaussian blur to estimate illumination
illumination = cv2.GaussianBlur(
    log_image,
    (0, 0),
    sigmaX=30
)

# Remove uneven illumination
corrected = log_image - illumination

# Convert back using exponential
corrected = np.expm1(corrected)

# Normalize to 0–255
corrected = cv2.normalize(
    corrected,
    None,
    0,
    255,
    cv2.NORM_MINMAX
)

corrected = corrected.astype(np.uint8)

# Display results
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Uneven Illumination")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(corrected, cmap="gray")
plt.title("Illumination Corrected")
plt.axis("off")

plt.show()