# -*- coding: utf-8 -*-
"""CO2AT2Q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VftJwmf8m8dOE-EfJPf33eKCEqvIBtq
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read satellite image
image = cv2.imread(
    "sample.jpg",
    cv2.IMREAD_GRAYSCALE
)

# Get image size
rows, columns = image.shape

# Apply Fourier Transform
fourier = np.fft.fft2(image)

# Shift low frequencies to center
fourier_shift = np.fft.fftshift(fourier)

# Create Gaussian low-pass filter
u = np.arange(rows) - rows / 2
v = np.arange(columns) - columns / 2

V, U = np.meshgrid(v, u)

# Cutoff frequency
D0 = 30

# Gaussian low-pass filter
filter_mask = np.exp(
    -(U**2 + V**2) / (2 * D0**2)
)

# Apply filter
filtered_frequency = (
    fourier_shift * filter_mask
)

# Shift back
inverse_shift = np.fft.ifftshift(
    filtered_frequency
)

# Apply inverse Fourier transform
filtered_image = np.fft.ifft2(
    inverse_shift
)

# Get real values
filtered_image = np.abs(
    filtered_image
)

# Display results
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Noisy Satellite Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(
    filtered_image,
    cmap="gray"
)
plt.title("Gaussian Low-Pass Output")
plt.axis("off")

plt.show()