# -*- coding: utf-8 -*-
"""CO2AT2Q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu-V5en2ItlaFrKuLAmd8OdE-7ThFB9C
"""

import cv2
import matplotlib.pyplot as plt

# Read noisy document
image = cv2.imread("sample.jpg", cv2.IMREAD_GRAYSCALE)

# Apply 3×3 median filter
filtered = cv2.medianBlur(image, 3)

# Display results
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Noisy Document")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(filtered, cmap="gray")
plt.title("Median Filter Output")
plt.axis("off")

plt.show()