# -*- coding: utf-8 -*-
"""CO2AT2Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDDiqh2vdSAgD7ZxylZsqK0RE9j7a0_h
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read grayscale image
image = cv2.imread("sample.jpg", cv2.IMREAD_GRAYSCALE)

# Find minimum and maximum intensity
min_value = np.min(image)
max_value = np.max(image)

# Apply contrast stretching
enhanced = ((image - min_value) / (max_value - min_value)) * 255

# Convert to unsigned integer
enhanced = enhanced.astype(np.uint8)

# Display images
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Original Low Contrast Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(enhanced, cmap="gray")
plt.title("Contrast Stretched Image")
plt.axis("off")

plt.show()