# -*- coding: utf-8 -*-
"""CO2AT2Q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qn7Ji9WgMPG-zzAD3ZoDoVhGX-QDMN60
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read blurred image
image = cv2.imread("/content/sample.jpg", cv2.IMREAD_GRAYSCALE)

# Apply Laplacian operator
laplacian = cv2.Laplacian(
    image,
    cv2.CV_64F
)

# Sharpen image
sharpened = image.astype(np.float64) - laplacian

# Limit values to 0–255
sharpened = np.clip(
    sharpened,
    0,
    255
)

# Convert to uint8
sharpened = sharpened.astype(np.uint8)

# Display results
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Blurred Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(sharpened, cmap="gray")
plt.title("Laplacian Sharpened Image")
plt.axis("off")

plt.show()