# -*- coding: utf-8 -*-
"""CO3AT2-14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6YetWwgB2F3ECxRs7rEJqb6aE2RJ0Pa
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Read multiple images
images = []

# Assuming there is a single image file named 'image.jpg' available
# and the intent is to process this image (or replicate its loading) for PCA.
# The original code expected multiple numbered images which were not found.
# We will use the existing '/content/image.jpg' for loading.

# Load the base image once
base_img_path = "/content/image.jpg"
base_img = cv2.imread(base_img_path, cv2.IMREAD_GRAYSCALE)

if base_img is None:
    print(f"Error: Could not load base image '{base_img_path}'. Cannot proceed.")
else:
    # Resize the base image
    base_img_resized = cv2.resize(base_img, (50, 50))

    for i in range(1, 6):
        # Add a small amount of random noise to create distinct images for PCA
        # Ensure noise has the same data type as the image to avoid issues.
        noise = np.random.normal(0, 5, base_img_resized.shape).astype(base_img_resized.dtype)
        noisy_img = np.clip(base_img_resized + noise, 0, 255) # Clip to image valid range
        images.append(noisy_img.flatten())

# Convert to NumPy array
if not images:
    print("Error: No images were loaded (or base image failed to load). Cannot proceed with PCA.")
else:
    data = np.array(images)

    print("Original feature dimension:", data.shape[1])

    # PCA with 95% information preservation
    # It's important that n_components is less than or equal to the number of samples (5 in this case)
    # and also less than or equal to the number of features. If n_components is set to a float (0-1),
    # it selects the number of components such that the amount of variance that needs to be explained is greater than the percentage specified.
    pca = PCA(n_components=0.95)

    reduced_data = pca.fit_transform(data)

    print("Reduced feature dimension:", reduced_data.shape[1])

    print("Explained variance ratio:")
    print(pca.explained_variance_ratio_)

    print("Total information preserved:",
          sum(pca.explained_variance_ratio_))

    # Reconstruct images
    reconstructed = pca.inverse_transform(reduced_data)

    # Display reconstructed images
    plt.figure(figsize=(12, 4))

    for i in range(len(images)):
        plt.subplot(1, 5, i + 1)

        # Ensure reconstructed data is clipped and converted to appropriate type for display
        img_to_display = reconstructed[i].reshape(50, 50).astype(np.uint8) # Convert to uint8 for imshow

        plt.imshow(img_to_display, cmap="gray")
        plt.title("Image " + str(i + 1))
        plt.axis("off")

    plt.tight_layout()
    plt.show()