# -*- coding: utf-8 -*-
"""CO3AT2-13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cEI50lSUjLljp4MyE1E5g9HwTa-YTf8
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read images
img1 = cv2.imread("j1.jpg")
img2 = cv2.imread("j2.jpg")

# Convert to grayscale
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# Add noise to second image
noise = np.random.normal(0, 25, gray2.shape).astype(np.uint8)
noisy_img2 = cv2.add(gray2, noise)

# Remove noise using Gaussian blur
filtered_img2 = cv2.GaussianBlur(noisy_img2, (5, 5), 0)

# SIFT feature detection
sift = cv2.SIFT_create()

kp1, des1 = sift.detectAndCompute(gray1, None)
kp2, des2 = sift.detectAndCompute(filtered_img2, None)

# Feature matching
bf = cv2.BFMatcher()

# Check if descriptors are found for both images
if des1 is None or des2 is None or len(des1) == 0 or len(des2) == 0:
    print("Error: Not enough descriptors found in one or both images to perform matching.")
    good_matches = [] # Initialize good_matches to an empty list
else:
    matches = bf.knnMatch(des1, des2, k=2)

    # Ratio test
    good_matches = []

    for m, n in matches:
        if m.distance < 0.7 * n.distance:
            good_matches.append(m)

# Draw matches
result = cv2.drawMatches(
    gray1, kp1,
    filtered_img2, kp2,
    good_matches, None,
    flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
)

# Display
plt.figure(figsize=(12, 6))
plt.imshow(result, cmap="gray")
plt.title("Feature Matching After Noise Removal")
plt.axis("off")
plt.show()

print("Number of good matches:", len(good_matches))