# -*- coding: utf-8 -*-
"""CO3AT2-15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqUxsIkuwj-VjRSL1e5o8hI2hFdeBVQ3
"""

import cv2
import matplotlib.pyplot as plt

# Read images
img1 = cv2.imread("j1.jpg")
img2 = cv2.imread("j2.jpg")

# Convert to grayscale
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB feature detector
orb = cv2.ORB_create()

# Detect features and descriptors
kp1, des1 = orb.detectAndCompute(gray1, None)
kp2, des2 = orb.detectAndCompute(gray2, None)

# Hamming distance for ORB binary descriptors
bf = cv2.BFMatcher(
    cv2.NORM_HAMMING,
    crossCheck=True
)

# Match descriptors
matches = bf.match(des1, des2)

# Sort matches based on distance
matches = sorted(
    matches,
    key=lambda x: x.distance
)

# Draw best matches
result = cv2.drawMatches(
    img1, kp1,
    img2, kp2,
    matches[:50],
    None,
    flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS
)

# Display
plt.figure(figsize=(14, 7))
plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
plt.title("ORB Feature Detection and Matching")
plt.axis("off")
plt.show()

print("Features in Image 1:", len(kp1))
print("Features in Image 2:", len(kp2))
print("Total Matches:", len(matches))
print("Best Matches Displayed:", min(50, len(matches)))