# -*- coding: utf-8 -*-
"""labexp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNM_xjpeVstNnXPpEcX2xV6sKqp0pzCp
"""

import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread('sample3.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 100, 200)
cv2.imwrite('Canny_Edges_3rd.jpg', edges)
cv2_imshow(edges)
cv2.waitKey(0)
cv2.destroyAllWindows()