# -*- coding: utf-8 -*-
"""labexp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4BFhJ873cwut2oqWRKgbsRNgTKYu3IJ
"""

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('sample2.jpg')
blur = cv2.GaussianBlur(image, (5, 5), 10)
cv2.imwrite('blurred_image.jpg', blur)
cv2_imshow(blur)
cv2.waitKey(0)
cv2.destroyAllWindows()