# -*- coding: utf-8 -*-
"""CO2AT1Q01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_J9lSfgA0VbRZDSMTPvcMT3EpVPE1miB
"""

import numpy as np

# Sample pixel values
pixels = np.array([0, 50, 100, 150, 200, 255])

# Negative transformation
negative = 255 - pixels

print("Original pixels:", pixels)
print("Negative pixels:", negative)