# -*- coding: utf-8 -*-
"""CO2AT1Q06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBXqSUMC26isYGY3HhrqGrHKcfmqozCS
"""

import numpy as np

# Sample frequency components
frequency = np.array([100, 80, 50, 30, 20])

# Create output with zeros
filtered = np.zeros(len(frequency))

# Retain only the first two components
filtered[0] = frequency[0]
filtered[1] = frequency[1]

print("Original frequency components:", frequency)
print("Filtered output:", filtered)