# -*- coding: utf-8 -*-
"""CO2AT1Q03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdzX7L4smXG0qBBk4Nlnbkbz0_nwhoEn
"""

import numpy as np

# Given histogram
histogram = np.array([2, 2, 4, 8])

# Total number of pixels
total_pixels = np.sum(histogram)

# Cumulative frequency
cumulative = np.cumsum(histogram)

# Cumulative distribution function
cdf = cumulative / total_pixels

# 3-bit image
L = 8

# Equalized intensity values
equalized = np.round((L - 1) * cdf).astype(int)

print("Histogram:", histogram)
print("Cumulative frequency:", cumulative)
print("CDF:", cdf)
print("Equalized intensity values:", equalized)