# -*- coding: utf-8 -*-
"""CO2AT1Q02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6Cjr8nIYm_NUPq2woxGTB-RSeVW5Cfn
"""

import numpy as np

# Sample pixel values
pixels = np.array([0, 1, 3, 7, 15])

# Constant
c = 1

# Log transformation
log_values = c * np.log(1 + pixels)

print("Original pixels:", pixels)
print("Log transformed values:", log_values)