# -*- coding: utf-8 -*-
"""CO2AT1Q04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZmgjZPJmsOKiQU3LicC1l_1qot6uStE
"""

import numpy as np

# Sample 3×3 image region
image = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Calculate average
new_center = np.mean(image)

print("Image region:")
print(image)

print("New center pixel value:", new_center)