# -*- coding: utf-8 -*-
"""CO2AT1Q08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LKLH1pxf3mFhfLRy6g5rfzQUUT673ch
"""

import numpy as np

# Sample 3×3 image matrix
image = np.array([
    [10, 10, 10],
    [20, 20, 20],
    [50, 50, 50]
])

# Horizontal Sobel mask
sobel = np.array([
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]
])

# Calculate gradient
gradient = np.sum(image * sobel)

print("Input matrix:")
print(image)

print("Sobel gradient:", gradient)