# -*- coding: utf-8 -*-
"""CO2AT1Q09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ni3HMZt9Hc56FprYETv9446jux2Bqw_9
"""

import numpy as np

# Pixel intensities
pixels = np.array([40, 45, 48, 50, 52, 55, 60])

# Seed value
seed = 50

# Threshold difference
threshold = 5

# Select pixels belonging to the region
region = pixels[np.abs(pixels - seed) <= threshold]

print("Pixel values:", pixels)
print("Seed:", seed)
print("Threshold difference:", threshold)
print("Pixels in region:", region)