# -*- coding: utf-8 -*-
"""CO2AT1Q05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOeYSP_Z2OFUyuAXt3d5geeP8-qD9GbC
"""

import numpy as np

# Sample image matrix
image = np.array([
    [10, 10, 10],
    [10, 50, 10],
    [10, 10, 10]
])

# Laplacian mask
laplacian = np.array([
    [0, -1, 0],
    [-1, 4, -1],
    [0, -1, 0]
])

# Apply mask
output = np.sum(image * laplacian)

print("Input image:")
print(image)

print("Laplacian output at center:", output)