# -*- coding: utf-8 -*-
"""labexp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqIB22E3yIFtEvW17s5BH_dpmzGvEK-p
"""

import cv2

import numpy as np
img = cv2.imread('sample4.jpeg')
kernel = np.ones((5,5), np.uint8)
dilated_img = cv2.dilate(img, kernel, iterations=1)
cv2.imwrite('Dilated_Image.jpg', dilated_img)