# -*- coding: utf-8 -*-
"""CO3AT1Q24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weRcTI5Nx-Rq05NUZLq9abBFJGhy585K
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Load images
images = []

for i in range(1, 6):
    img = cv2.imread("image" + str(i) + ".jpg",
                     cv2.IMREAD_GRAYSCALE)

    # Check if image was loaded successfully
    if img is None:
        print(f"Error: Could not load image{'image' + str(i) + '.jpg'}. Please ensure the file exists.")
        continue # Skip to the next image if loading failed

    img = cv2.resize(img, (50, 50))

    images.append(img.flatten())

# Convert to array
if not images:
    print("No images were loaded. Cannot proceed with PCA.")
else:
    data = np.array(images)

    print("Original Feature Dimension:", data.shape[1])

    components = [2, 3, 4]

    for n in components:

        pca = PCA(n_components=n)

        reduced = pca.fit_transform(data)

        print("\nNumber of Components:", n)
        print("Reduced Feature Dimension:", reduced.shape)
        print("Information Preserved:",
              np.sum(pca.explained_variance_ratio_))

        # Reconstruct images
        reconstructed = pca.inverse_transform(reduced)

        plt.figure(figsize=(10, 2))

        for j in range(len(images)):
            plt.subplot(1, 5, j + 1)

            img = reconstructed[j].reshape(50, 50)

            plt.imshow(img, cmap="gray")
            plt.axis("off")

        plt.suptitle("PCA Components = " + str(n))
        plt.show()