# -*- coding: utf-8 -*-
"""CO3AT122.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtOf7OIf8Zg4HNxMvtqLV1aQMhIDCfkJ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img1 = cv2.imread("image1.jpg", cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread("image2.jpg", cv2.IMREAD_GRAYSCALE)

def match_features(detector_name):
    if detector_name == "SIFT":
        detector = cv2.SIFT_create()
        norm = cv2.NORM_L2
    else:  # ORB
        detector = cv2.ORB_create(2000)
        norm = cv2.NORM_HAMMING

    kp1, des1 = detector.detectAndCompute(img1, None)
    kp2, des2 = detector.detectAndCompute(img2, None)

    bf = cv2.BFMatcher(norm)
    knn_matches = bf.knnMatch(des1, des2, k=2)

    # Lowe's ratio test to separate good matches from false matches
    good = []
    for m, n in knn_matches:
        if m.distance < 0.75 * n.distance:
            good.append(m)

    # Estimate homography with RANSAC to count geometric inliers
    inliers = 0
    if len(good) >= 4:
        src = np.float32([kp1[m.queryIdx].pt for m in good]).reshape(-1, 1, 2)
        dst = np.float32([kp2[m.trainIdx].pt for m in good]).reshape(-1, 1, 2)
        H, mask = cv2.findHomography(src, dst, cv2.RANSAC, 5.0)
        inliers = int(mask.sum()) if mask is not None else 0

    result = {
        "detector": detector_name,
        "keypoints_img1": len(kp1),
        "keypoints_img2": len(kp2),
        "raw_matches": len(knn_matches),
        "good_matches_ratio_test": len(good),
        "ransac_inliers": inliers,
        "false_matches": len(good) - inliers,
    }
    match_img = cv2.drawMatches(img1, kp1, img2, kp2, good[:50], None,
                                 flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    cv2.imwrite(f"matches_{detector_name}.png", match_img)
    return result

for name in ["SIFT", "ORB"]:
    r = match_features(name)
    print(r)

"""### Feature Matching Results Visualizations"""

import matplotlib.pyplot as plt

# Display the SIFT matches image
plt.figure(figsize=(12, 6))
sift_matches_img = cv2.imread("matches_SIFT.png")
plt.imshow(cv2.cvtColor(sift_matches_img, cv2.COLOR_BGR2RGB))
plt.title("SIFT Feature Matches")
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt

# Display the ORB matches image
plt.figure(figsize=(12, 6))
orb_matches_img = cv2.imread("matches_ORB.png")
plt.imshow(cv2.cvtColor(orb_matches_img, cv2.COLOR_BGR2RGB))
plt.title("ORB Feature Matches")
plt.axis('off')
plt.show()