# -*- coding: utf-8 -*-
"""CO3AT1Q25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKF3uedLY6dXbZE5olv_7oLQYdwelrhl
"""

import cv2
import matplotlib.pyplot as plt

# --------------------------------
# Stage 1: Read Image
# --------------------------------

image = cv2.imread("image.jpg")

# --------------------------------
# Stage 2: Preprocessing
# --------------------------------

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Remove noise using Gaussian Blur
blur = cv2.GaussianBlur(gray, (5, 5), 0)

# --------------------------------
# Stage 3: Edge Detection
# --------------------------------

edges = cv2.Canny(blur, 100, 200)

# --------------------------------
# Stage 4: Feature Extraction
# --------------------------------

# ORB feature detector
orb = cv2.ORB_create()

keypoints, descriptors = orb.detectAndCompute(
    gray, None
)

# Draw keypoints
feature_image = cv2.drawKeypoints(
    gray,
    keypoints,
    None,
    color=None,
    flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS
)

# --------------------------------
# Display all stages
# --------------------------------

plt.figure(figsize=(12, 10))

plt.subplot(2, 2, 1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("1. Original Image")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(blur, cmap="gray")
plt.title("2. Preprocessed Image")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(edges, cmap="gray")
plt.title("3. Edge Detection")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(cv2.cvtColor(feature_image, cv2.COLOR_BGR2RGB))
plt.title("4. Feature Extraction")
plt.axis("off")

plt.tight_layout()
plt.show()

# Print feature information
print("Number of Keypoints Detected:",
      len(keypoints))

if descriptors is not None:
    print("Descriptor Shape:",
          descriptors.shape)
else:
    print("No descriptors detected.")