# -*- coding: utf-8 -*-
"""CO3AT1Q23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UuK8Cb_pN3tz9Aqc81TNDQVTZTq7I7L
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Read image
image = cv2.imread("image.jpg", cv2.IMREAD_GRAYSCALE)

# Resize image
image = cv2.resize(image, (100, 100))

# Convert image into 1D feature vector
# Original: data = image.reshape(1, -1)
# Fix: Treat each row of the image as a sample
data = image

print("Original Feature Dimension:", data.shape[1])

# Different PCA component values
components = [10, 25, 50, 75, 100]

plt.figure(figsize=(15, 8))

for i, n in enumerate(components):

    # Apply PCA
    pca = PCA(n_components=n)

    transformed = pca.fit_transform(data)

    # Reconstruct image
    reconstructed = pca.inverse_transform(transformed)

    # The reconstruction will have the original image shape (100, 100)
    # reconstructed = reconstructed.reshape(100, 100) # This line is no longer strictly needed if data is (100,100)

    # Display result
    plt.subplot(2, 3, i + 1)
    plt.imshow(reconstructed, cmap="gray")
    plt.title("Components = " + str(n))
    plt.axis("off")

    print("\nComponents:", n)
    print("Reduced Dimension:", transformed.shape)
    print("Explained Variance:",
          np.sum(pca.explained_variance_ratio_))

plt.tight_layout()
plt.show()